const PREDEFINED_ITEMS = {
  'Carpentry': [
    '12MM PLY 8x4 (Ecotec/MR)',
    '18MM Ply 8X4',
    '25MM BOARD 8x4 (Ecotec/MR)',
    'Beeding 2nd 35X6',
    'Beeding 2nd 35x10',
    'FEVICOL SH',
    'HITEX',
    'Abrow Tape',
    'Nail 14 no. 2\'',
    'Nail 14 no. 1.5',
    'Nail 17no. 1\' HL',
    'Nail 19 NO. 1\' HL',
    '2 Nos Tie Rod Wiser Nut Board 3.5"',
    'Nail 17 no. 1.25',
    '75/10 screw',
    '60/10 screw',
    '32/6 screw',
    '50/6 screw',
    '25/6 screw',
    'gulli/gujji'
  ],
  'False Ceiling': [
    'Gypsum Board (Saint Gobian/Boral)',
    'Stud 12\'',
    'Floor 12\'',
    '1\' Black Screw',
    'Jointing Tape',
    'PVC Grip',
    'Wooden Screw 1.5"'
  ],
  'Painting': [
    'Putty',
    'Acrylic Putty',
    'Metal Primer Asian',
    'Asian Wall Primer Water Base',
    'Asian Primium Base',
    'Primium Wall Blue Colour 7325',
    'Shutter/Grill Oxford Blue 0119',
    'Counter Grill Asian White Paint',
    'Sand Paper 150 no.',
    'Roll Paper 100 n0.',
    'Cloth',
    'Brown Paint 100 ml',
    'Tarpin',
    'Thinner'
  ],
  'Aluminium Work': [
    'Aluminium Section 2 1/2\'x 1 1/2\'',
    'door vertical 10ft',
    'Door Bottom',
    'Clip',
    'Angle',
    'Rubber',
    'Clear silicon',
    'patam section 7ft',
    'patam section 4ft',
    'tie rod'
  ],
  'Modular': [
    'Manager Table',
    'Executive Table',
    'Cash/Gold Counter',
    'Pedestal Wooden',
    'Printer Table',
    'Laminate',
    'Ozone Handle',
    'Ozone Door Closer',
    'Godrej All Door Lock',
    'Godrej Inside/Outside Latch',
    'Shutter Pad Lock',
    'File Candy',
    'Acrylic Frame',
    'Folding Bracket',
    '5\' SS Hinge',
    'Stopper',
    'Lining Film',
    '2\' Mirror Screw',
    '32/8 Star Screw',
    'Half Inch Black Screw',
    '1.5 Black Screw',
    '19/8 Star screw',
    'White Board',
    'Notice Board Blue',
    'MDF Particle Board (Chair Band)',
    'Cylindrical Lock',
    '6\' SS Handal'
  ],
  'Electrical': [
    'TPN 40 Amp 4 pole L & T',
    '63 Amp Busbar',
    'Singal Pole MCB 10 Amp L & T',
    'Single Pole 16 Amp MCB L & T',
    '25 Amp Dp L & T',
    '40 amp RCCB 4 pole With Box L & T',
    '4 Way SPN Box Double Door L & T',
    '2 Way DP MS Box SPN Single Door',
    '8 Way SPN Box Double Door L & T',
    '6 Square mm Copper Luxe Ring Type',
    '6 Square mm Copper Luxe Pin Type',
    '1 Sqaure mm Wire 90 Mtr Policap',
    '1.5 Square mm Wire 90 Mtr Policap',
    '2.5 Square mm Wire Policap',
    '4 mm Wire Policap ( 10 mtr red + 10mtr black )',
    'Celling Rose (anchor )',
    'D Hook',
    '16 Amp Switch Grate White',
    '16 amp Socket Grate White',
    '6 Amp Switch Grate White',
    '6 Amp Socket Grate White',
    'bell switch ( switch type ) Grate White',
    '16 Amp Top Anchor',
    '5 Amp Top Anchor',
    '12 Module PVC Box Local',
    '12 Module PVC Plate Local',
    '6 Module PVC Box Local',
    '6 Module PVC Plate Local',
    '8 Module PVC Box Local',
    '8 Module PVC Plate Grate White',
    '3 Module PVC Box Grate White',
    '3 Module PVC Plate Grate White',
    '2 Module PVC Box Grate White',
    '2 Module PVC Plate Grate White',
    '1 module plate Grate White',
    'calling bell ding dong Anchor',
    'Copper Bolt',
    '25 Amp Switch Type MCB Grate White',
    'Fan Regulator Switch Type Grate White',
    'Dummy Plate Grate White',
    'Tape',
    'PVC Grip ( hariom )',
    'Earthing Electrod 2 mtr 50 mm Dia',
    'Chemical Bag 25 kg',
    '20mmChaina Clip',
    'Chaina Clip 25 mm',
    '2\' Tubelight philips',
    '4\' Tubelight philips',
    'PVC Conduit Pipe (anchor, policap , finolex)',
    'PVC Band 1" (anchor, policap , finolex)',
    'PVC Junction Box (anchor, policap , finolex)',
    'PVC Cassing 1"',
    'Celling Fan 48" Cromton',
    'Exhaust Fan 9" metal Cromton',
    'Exhaust Fan 12" (PVC 300 mm ) Bajaj',
    '10 Sq mm 4 core armet cable',
    '10 mm cooper taar (earthing )'
  ]
};

module.exports = { PREDEFINED_ITEMS };
